services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  app:
    build: .

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: testdb
      DB_USER: user
      DB_PASSWORD: password

      APP_PORT: 8080

    ports:
      - "8080:8080"

    depends_on:
      - postgres
