server:
  port: 8080

spring:
  application:
    name: wallet-test-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:wallet_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: never
      data-locations: classpath:data/*.sql

  liquibase:
    change-log: classpath:/db/changelog/changelog/db.changelog-master.xml